name: GCR-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'  

    - name: Install dependencies
      run: npm install  

    - name: Authenticate
      env: 
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} 
      run: |
        echo $GCP_SA_KEY > ./get-safle-e9bb009adc35.json
        gcloud auth activate-service-account --key-file=./get-safle-e9bb009adc35.json
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-south2-docker.pkg.dev
        gcloud auth configure-docker asia-south2-docker.pkg.dev
        rm ./get-safle-e9bb009adc35.json
        
    - name: Build Docker image
      run: |
        docker build . -t asia-south2-docker.pkg.dev/get-safle/get-safle/app-image:${{ github.ref_name }}-${GITHUB_SHA::7}
    
    - name: Push Docker image to Google Artifact Registry
      run: |
        docker push asia-south2-docker.pkg.dev/get-safle/get-safle/app-image:${{ github.ref_name }}-${GITHUB_SHA::7}

    - name: Run unit tests
      run: npm test  

    - name: Deploy with Terraform
      run: |
        terraform init
        terraform apply -auto-approve

    